# .github/workflows/build.yml
name: Publish Artifacts for Quicksight and Athena Views
#on:

  # pull_request:
  #   branches:
  #     - dev
      
#  push:
#    branches:
  # workflow_dispatch:     
  #   inputs:
  #     environment:
  #       description: GitHub Environment where Job Will Run
  #       required: true
  #       type: string
  on:
    workflow_dispatch:
      inputs:
        environment:
          description: 'Select the target environment'
          required: true
          type: choice
          options:
            - dev
            - qa
            - production
      
jobs:
  publish-artifacts_dev:
    if: ${{ github.event.inputs.environment == 'dev' }}
    name: Publish Artifacts for Quicksight and Athena Views
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello from Build
        run: echo "dev:Hello from build.yml"

  publish-artifacts_qa:
    if: ${{ github.event.inputs.environment == 'qa' }}  
    name: Publish Artifacts for Quicksight and Athena Views
    runs-on: ubuntu-latest  
    steps:
      - name: Print Hello from Build
        run: echo "prod:Hello from build.yml"
      
