# .github/workflows/build.yml
name: Publish Artifacts for Quicksight and Athena Views


  # workflow_dispatch:     
  #   inputs:
  #     environment:
  #       description: GitHub Environment where Job Will Run
  #       required: true
  #       type: string
on:
  workflow_dispatch:
    inputs:
      deploy_to_dev:
        description: 'Deploy to Development environment?'
        required: false
        type: boolean
        default: false
      deploy_to_qa:
        description: 'Deploy to qa environment?'
        required: false
        type: boolean
        default: false

      deploy_to_prod:
        description: 'Deploy to Production environment?'
        required: false
        type: boolean
        default: false  

  
  release:
    types: [published]       
          
jobs:
  # publish-artifacts_dev:
  #   if: ${{ github.event.inputs.deploy_to_dev == 'true' }}
  #   name: Publish Artifacts for Quicksight and Athena Views
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Print Hello from Build
  #       run: echo "dev:Hello from build.yml"

  publish-artifacts_dev:
    uses: ./.github/workflows/dev.yml

  required_approval_for_prod:
    
    runs-on: ubuntu-latest
    needs: publish-artifacts_dev
    environment:
      name: prd  # Protects PRD with GitHub Environments approval
      url: https://github.com/${{ github.repository }}/tree/${{ github.ref_name }}
   
    outputs:
      result_prd: ${{ steps.setresult.outputs.result_prd }}
    steps:
      - name: Set result
        id: setresult
        run: echo "result_prd=success" >> $GITHUB_OUTPUT  

  publish-artifacts_qa:
    uses: ./.github/workflows/qa.yml
    needs: required_approval_for_prod
    # if: ${{ github.event.inputs.deploy_to_qa == 'true' }}  
    # name: Publish Artifacts for Quicksight and Athena Views
    # runs-on: ubuntu-latest  
    # steps:
    #   - name: Print Hello from Build
    #     run: echo "qa:Hello from build.yml"
  publish-artifacts_prod:
    if: ${{ (github.event.inputs.deploy_to_prod == 'true' && github.ref == 'refs/heads/main')  || (github.event_name == 'release' && github.event.action == 'published') }}
    needs: publish-artifacts_qa
    name: Publish Artifacts for Quicksight and Athena Views
    runs-on: ubuntu-latest  
    steps:
      - name: Print Hello from Build
        run: echo "prod:Hello from build.yml"
      
