name: Reusable Workflow 1

on:
  workflow_call:
    outputs:
      result:
        description: "Output from workflow 1"
        value: ${{ jobs.example.outputs.some_output }}

jobs:
  example:
    runs-on: ubuntu-latest
    outputs:
      some_output: "success"
    steps:
      - run: echo "Workflow 1 completed"

      
