name: reusable-workflow1

on:
  workflow_call:
    
  push:
    branches:
      - dev

jobs:
  example:
    runs-on: ubuntu-latest
    outputs:
      some_output: "success"
    steps:
      - run: echo "Workflow 1 completed"

      
