name: Reusable Workflow

on:
  workflow_call:
    inputs:
      environment:
        description: "Target Environment"
        required: true
        type: string
      awsRegionCode:
        description: "AWS Region Code"
        required: true
        type: string
      awsRegionAbbreviation:
        description: "AWS Region Abbreviation"
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ inputs.awsRegionCode }}
        run: |
          echo "Checking AWS credentials..."
          if [ -z "$AWS_ACCESS_KEY_ID" ]; then
            echo "AWS_ACCESS_KEY_ID is not set!"
            exit 1
          fi
          if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
            echo "AWS_SECRET_ACCESS_KEY is not set!"
            exit 1
          fi
          aws sts get-caller-identity --region $AWS_REGION