name: Caller Workflow

on:
  push:
    branches:
      - dev
  workflow_dispatch: # Trigger manually for testing

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/called.yml # Points to the reusable workflow in the same repo
    environment: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      environment: dev
      awsRegionCode: us-west-2
      awsRegionAbbreviation: wus2
      