# .github/workflows/deploy-to-env.yml
# .github/workflows/deploy-to-env.yml
name: Deploy to Environment

on:
  push:
    branches:
      - dev

  workflow_dispatch:
    inputs:
      environment:
        description: "Target Environment (dev, tst, qa, prd)"
        required: true
        type: choice
        options:
          - dev
          - tst
          - qa
          - prd

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Environment
        run: echo "Deploying to ${{ github.event.inputs.environment || 'dev' }}"

  call-lambda-deployment:
    needs: deploy
    uses: ./.github/workflows/lambda-deployment.yml
    with:
      environment: ${{ github.event.inputs.environment || 'dev' }}
      awsRegionCode: 'us-west-2'
      awsRegionAbbreviation: 'wus2'
      s3ArtifactBucketSuffix: 's3-tf-artifacts'
      s3ArtifactBucketFolder: 'pipeline-artifact'
      s3LambdaObjectKey1: 'ccc_audit_call_lambda.zip'
      lambdaFunctionName1: 'lambda-audit-call'
    secrets: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
