name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: build
      run: echo "hello world"
 
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: first build
      run: echo "first build"
